### PR TITLE
Add nop

### PR DESCRIPTION
**Pull request by titzer**

### CODE REVIEW

**Comment by binji** [comment]
lgtm

**Comment by sunfishcode** [comment]
This is the kind of thing where it'd be really great if we had a more explicit process around the binary format design, because the utility of a nop is highly dependent on the binary encoding strategy.

**Comment by lukewagner** [comment]
So then what was the use case for nop?

**Comment by jfbastien** [comment]
Rationale.md would be a good place for an explanation of not-super-obvious things such as this?

**Comment by kg** [comment]
```nop```'s utility should be obvious for people who are familiar with the history of similar instructions in native instruction sets, or people who have written compilers. I'm kinda shocked that we keep discussing whether to keep it or not, given that by its definition we don't need to do any work to implement it other than have the ast node lying around. It doesn't do anything.

I'll try to put together a PR that adds a rationale to Rationale.md.

**Comment by lukewagner** [comment]
> nop's utility should be obvious for people who are familiar with the history of similar instructions in 
> native instruction sets, or people who have written compilers.

Let's keep this polite.

**Pull request merged**
