### PR TITLE
Put f32.const before f64.const, for consistency.

### PR DESCRIPTION
**Pull request by sunfishcode**
This is for the binary_0xc branch, and is one step of a broader opcode reorganization.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm

**Comment by rossberg-chromium** [comment]
I'm fine with all the changes you have suggested so far. But instead of making many tiny changes individually, how about a single comprehensive PR for reorganising the opcode space? That would help seeing the big picture and not fragmenting the discussion.

**Comment by titzer** [comment]
Shall we do this in 0xD?

**Comment by rossberg-chromium** [comment]
Should be subsumed by #826 now.

**Pull request closed without merging**
