### PR TITLE
Add section to find events or talks related to WebAssembly

### PR DESCRIPTION
**Pull request by jbondc**
Found this online but never heard of the event.

Useful to have this in the repo for anyone following WebAssembly.

### CODE REVIEW

**Comment by kripken** [comment]
Can also add https://kripken.github.io/talks/wasm.html#/

I'd suggest taking out the location (seems unnecessary).

**Comment by jbondc** [comment]
Almost added ```Binaryen Rhymes with Targaryen``` as the event description, feel free to add that in :wink:

**Comment by jfbastien** [comment]
Could you add also videos where available, and make these proper links (not just the URL itself)?

**Comment by jbondc** [comment]
Anything else?

**Comment by jfbastien** [comment]
@jbondc sorry, github doesn't send notifications when you push an update, so I hadn't seen this.

**Pull request merged**
