### PR TITLE
Create w3spec.bib

### PR DESCRIPTION
**Pull request by NANASHI0X74**
originally by @jendrikw, I just submitted the pull request. Does the bibtex item look fine? should the file be named w3spec.bib or maybe WASMStandard.bib or WASMSpec.bib or something like that?

### CODE REVIEW

**Comment by binji** [comment]
cc @ericprud

**Comment by rossberg** [comment]
Having this makes sense, although the spec repo would be the more appropriate place for it, especially so that we can update it along with the spec itself.

Also, I should probably be listed as editor rather than author, since future editions will incorporate other people's contributions.

As for file name, perhaps `wasm-specs.bib`? Plural because we may add more versions or API specs in the future. Certainly no name misspelling Wasm in all-caps. :)

**Comment by NANASHI0X74** [comment]
Is there an author then? I have the impression that the academic people I know usually want an author for sources...

**Comment by rossberg** [comment]
Not necessarily. Books may either have an author or an editor, proceedings have only editors. See [here](https://www.openoffice.org/bibliographic/bibtex-defs.html).

FWIW, `report` is not an official bibtex entry type. Maybe use `misc` instead, or `book`.

Would also make sense to add a `year` entry, since `date` also isn't standard.

**Comment by jendrikw** [comment]
We may want to consider having two files, one that is strictcly conforming to bibtex (using `misc` and `year`), and one for biblatex (which can use features like `date`).

**Comment by NANASHI0X74** [comment]
maybe it can be one file with comments? Most people I know have a single file for bibliography anyway where they paste all their bibtex items into (including me). Not sure if that's according to best practice, if there are any.
Personally, after my first experience with Latex, I get the impression that the whole ecosystem is kind of a mess and that for many things there aren't any solid best practices 😅 That may just be me though.

**Comment by sunfishcode** [comment]
This PR was replaced by https://github.com/WebAssembly/spec/pull/1204, which is now merged.

**Pull request closed without merging**
