### PR TITLE
Add memory/table import validation note

### PR DESCRIPTION
**Pull request by lukewagner**
This PR adds a clarification as suggested by #943.

### CODE REVIEW

**Comment by rossberg-chromium** [comment]
LGTM, but I just noted that for symmetry, we should also change step 4.ii.a about checking functions signatures into such a note, since conceptually that is an analogous import type check performed in Eval.init.

**Comment by lukewagner** [comment]
Ah, good observation.

**Comment by rossberg-chromium** [comment]
LGTM

**Comment by lukewagner** [comment]
@Cellule Is this what you were looking for?

**Comment by Cellule** [comment]
LGTM thanks !

**Pull request merged**
