### PR TITLE
Clarify that br_table has an optional argument

### PR DESCRIPTION
**Pull request by rossberg-chromium**
To adjust with AstSemantics and spec, see #658.

### CODE REVIEW

**Comment by JSStats** [comment]
Personally I see little compelling use case for this and wasm already has local variables to meet the use case which are needed anyway for dealing with multiple values.

I would be interested to know the current think on an 'operator table' which might allow developers to explore a `br_table` opcode without a value even with this change and to allow both options to be explored?

**Comment by kripken** [comment]
lgtm

@JSStats: some investigation of the benefits of br values is now in #667 (not specifically for br_table though).

**Comment by lukewagner** [comment]
lgtm

**Comment by titzer** [comment]
lgtm

**Pull request merged**
