### PR TITLE
Make `grow_memory` return the old memory size.

### PR DESCRIPTION
**Pull request by sunfishcode**
This implements the discussion in #525.

### CODE REVIEW

**Comment by lukewagner** [comment]
lgtm (still interested in discussing error return, but that could be a separate PR)

**Comment by jfbastien** [comment]
Can you also add a rationale (to rationale.md) for the threading case?

**Comment by sunfishcode** [comment]
@jfbastien Rationale added.

**Comment by jfbastien** [comment]
lgtm

**Comment by sunfishcode** [comment]
Merging with lgtms here and general agreement in #525. We can indeed discuss an error return in a separate issue/PR.

**Pull request merged**
