### PR TITLE
Clarify generativity of JS host functions values

### PR DESCRIPTION
**Pull request by rossberg-chromium**
Address #920. This appears to be the simplest way to specify it, and avoids aliasing in the index space as well as committing the core Wasm spec to host functions having identity.

Note: In Ocaml spec interpreter terms this is saying that closure equality is defined as follows:
```
let equal (cl1 : closure) (cl2 : closure) =
  match cl1, cl2 with
  | AstFunc (inst1, f1), AstFunc (inst2, f2) -> inst1 == inst2 && f1 = f2
  | _, _ -> cl1 == cl2
```
(Note the use of physical equality `==` vs structural equality `=`.)

### CODE REVIEW

**Comment by jfbastien** [comment]
Is this ready to go?

**Comment by rossberg-chromium** [comment]
Well, still pending review volunteers.

**Comment by jfbastien** [comment]
Can you rebase?

**Comment by rossberg-chromium** [comment]
Done.

**Comment by lukewagner** [comment]
lgtm

**Pull request merged**
