### PR TITLE
Binary 0xc

### PR DESCRIPTION
**Pull request by titzer**
Support for binary 0xC has landed in Firefox and Chrome, and the ml-proto spec is ready, so I think it's time we merged this as a signal that it's official.

### CODE REVIEW

**Comment by lukewagner** [comment]
lgtm

**Comment by titzer** [comment]
Both Andreas's over here are OOO, so if I can get another LGTM, I'll merge it.

**Comment by titzer** [comment]
Looks like a git log dump. I can remove it.

**Comment by jfbastien** [comment]
lgtm

**Pull request merged**
