### PR TITLE
Unknown sections must be uniquely named

### PR DESCRIPTION
**Pull request by jfbastien**
This is left unspecified. Unique naming seems like the right answer.

### CODE REVIEW

**Comment by titzer** [comment]
I see the argument for this, I don't think engines should be required to enforce this constraint. For example, it'd be unfortunate to have to keep a hashset of all unknown section names just to detect collisions to enforce this.

**Comment by jfbastien** [comment]
I don't really care either way, as long as we specify the expectation.
A linear search in an array is probably way faster than a hash set in the case that matters.

**Comment by lukewagner** [comment]
Given the preceding statement that "Unknown sections are ignored by the WebAssembly implementation, and thus validation errors within them do not invalidate a module.", I think the "must" is a bit ambiguous: it usually means validation error but here I don't think we want to create one special way that user-defined sections are validated.  How about "should"; that sets an expectation.

**Comment by jfbastien** [comment]
"should" is kind of horrible standards weaselry IMO. One or the other is good, but the middle ground isn't.

**Comment by sunfishcode** [comment]
I'm expecting we'll add this as a hard requirement in [convention documents](https://github.com/WebAssembly/tool-conventions/), as needed, as we start defining linking and other conventions. For example if we have a document that says that a section named "linking.static.relocations" (or whatever) contains relocations for static linking according to a certain convention, that same document could require that there be at most one section per module with that name in any object participating in the convention.

It's also possible that there will be situations where we don't need or want the uniqueness requirement. It would depend on the nature of the sections and the tools that will be processing them.

I guess this does raise a question: WebAssembly currently defines the "name" section as an official user-defined section. Should the spec specify how implementations should interpret the presence of mutiple "name" sections in a single module?

**Comment by binji** [comment]
Along those lines, is there a defined location for the "name" section?

**Comment by lukewagner** [comment]
Yeah, I was also thinking that perhaps one day we may want to allow multiple sections of a single type for specific section types (esp. for user-defined sections).  In that case, each section would specify whether it was valid to have more than one as part of that sections' validation rules.  Since all known sections may only appear once, it makes sense to say it once and for all.  But for user-defined sections, it's probably better to keep things open-ended and just say, in the names section, "may only appear once".

@binji You're right, that should also be stated in the Names section.  For us, the requirement is "after the Data section".

**Comment by jfbastien** [comment]
> @binji You're right, that should also be stated in the Names section. For us, the requirement is "after the Data section".

"requirement"? You fail validation if it's before, or you just ignore it?

**Comment by lukewagner** [comment]
Yes :)  Validation errors in user-defined sections don't cause the entire module to fail to validate.  So "only one" and "after data section" would just be two additional constraints in addition to all the existing validation criteria of a Names sections.

**Comment by jfbastien** [comment]
Names section is starting to sounds like a Real Section which we're trying to specify 😕

**Comment by binji** [comment]
wabt currently allows it anywhere after the function section. But if it occurs before then it is just ignored.

**Comment by jfbastien** [comment]
Ping, does anyone really care about the polarity of this? What I propose seems like the most consistent approach.

**Comment by lukewagner** [comment]
I'd propose removing the line added and instead adding one to the Names section that says "The Names section may only appear once and only after the Data section"

**Comment by lukewagner** [comment]
(and to be clear, that line would go after the existing one that says "Like all unknown sections, a validation error in this section does not cause validation of the module to fail." and thus it doesn't force checking or a validation error)

**Comment by jfbastien** [comment]
In that case, the line I add should also be reworded to say that unknown sections don't have to appear at most once.

**Comment by lukewagner** [comment]
sgtm

**Comment by jfbastien** [comment]
Updated as suggested, PTAL.

**Comment by lukewagner** [comment]
Thanks, lgtm

**Pull request merged**
