### PR TITLE
Reference the Source Map RFC repo from FutureFeatures.md

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by kripken** [comment]
Thanks! Can you please use the same linking format as in the rest of that document, though?

**Comment by fitzgen** [comment]
@kripken done!

**Comment by kripken** [comment]
lgtm, thanks. Let's wait a little to give some other people on this repo a chance to review this too.

**Comment by MikeHolman** [comment]
I'm ok linking to it, but I wish the Source Map RFC repo had a little more detail about what it is trying to accomplish. Right now when I follow the link there isn't even a full sentence about its purpose in the readme.

**Comment by jfbastien** [comment]
Agreed with @MikeHolman: I love links, but this one needs more information to be useful to readers. At least a populated README!

**Comment by fitzgen** [comment]
I expanded the README a little bit. Work going into the Source Map spec has historically been incredibly informal, and I think this is a reflection of that.

**Comment by lukewagner** [comment]
Btw, Nick, could you join the [W3C CG](https://www.w3.org/community/webassembly/) before this PR is merged?  We need to add this to Contributing.md, but that is the legal framework that protects the work in this repo.

**Comment by fitzgen** [comment]
> Btw, Nick, could you join the W3C CG before this PR is merged?

Alright, I requested an account. It needs further review. Will update when I hear back.

**Comment by fitzgen** [comment]
> Alright, I requested an account. It needs further review. Will update when I hear back.

I have requested to be nominated to WebAssembly Community
Group.

**Comment by jfbastien** [comment]
Thanks @fitzgen, you are indeed in the group :-)

**Pull request merged**
