### PR TITLE
Nondeterminism: has_feature

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by sunfishcode** [comment]
lgtm

**Comment by kripken** [comment]
Perhaps overly pedantic, but this is nondeterministic in the same sense that calling an outside function is nondeterministic, and that isn't mentioned on the list, because it is obvious. Not opposed to this, but if we are going for a full list here, do we need external methods too? Or is there a subtle difference I am missing?

**Comment by sunfishcode** [comment]
`has_feature` is presently spec'd as an opcode in the platform itself, which to me is what qualifies it for inclusion here, as opposed to API calls to the outside world.

**Comment by jfbastien** [comment]
I moved the API discussion to Rationale.md in a previous PR:

> There are a few obvious cases where nondeterminism is essential to the API, such as random number generators, date/time functions or input events. The WebAssembly specification is strict when it comes to other sources of limited local nondeterminism of operations: it specifies all possible corner cases, and specifies a single outcome when this can be done reasonably.

**Comment by kripken** [comment]
Ah, I see, thanks.

**Pull request merged**
