### PR TITLE
Make Instance.exports a getter

### PR DESCRIPTION
**Pull request by lukewagner**
As discussed in #1007.

### CODE REVIEW

**Comment by saambarati** [comment]
Do we want to specify configurable/enumerable explicitly? Or do we want to use ECMA's defined values?

**Comment by domenic** [comment]
It seems like the spec is assuming some fallback, either to the ES-spec defined values, or the Web IDL-spec defined ones. It's not clear which. But for example no methods have their property descriptors specified, so I am assuming there is some fallback.

**Comment by saambarati** [comment]
@domenic The defaults are specified in tc39. I'm just wondering if we want to use the defaults or not.

**Comment by domenic** [comment]
Yeah, one set of defaults is specified there, another is specified in Web IDL. I too am not sure which defaults WebAssembly wants to use.

**Comment by saambarati** [comment]
Gotcha. I didn’t realize Web IDL had different defaults. I think it’s a good idea to define what we want in Wasm in the spec.

**Comment by jfbastien** [comment]
Right, all accessors seem to not specify a default.

**Comment by jfbastien** [comment]
This is unclear, needs discussion. Moving to #1069.

**Pull request merged**
