### PR TITLE
Add a code of ethics and professional conduct

### PR DESCRIPTION
**Pull request by jfbastien**
WebAssembly is growing. There haven't been any regretable events, but it's been suggested that we make this community a welcoming one up-front by having a code of ethics and professional conduct.

### CODE REVIEW

**Comment by jfbastien** [comment]
@lukewagner @abchatra please take a look.

I'm trying to get a W3C mailinglist specifically to contact the chairs, and will update the (not so helpful) link once we have such mailing list.

**Comment by jfbastien** [comment]
W3C's Ian Jacobs was super helpful in tuning this, and creating the chairs mailing list.

**Comment by kg** [comment]
Looks super good to me. Thanks Ian and JF.

**Comment by jfbastien** [comment]
Merging, we can iterate on this.

**Comment by abchatra** [comment]
Looks good to me. Thanks folks!

**Comment by lukewagner** [comment]
Sorry for delay, lgtm too, thanks!

**Pull request merged**
