### PR TITLE
New logo for WA

### PR DESCRIPTION
**Pull request by armanx64**
New logo for WebAssembly. 
Fast and strong, simple and futuristic same time.
I made it in vector format, so you can recolor it as you want for any purpose. 
Licence is a MIT.

### CODE REVIEW

**Comment by jfbastien** [comment]
@armanx64, thanks for the suggestion, but WebAssembly isn't ready to have a logo yet. It's a cool looking logo though! I suggest adding your suggestion to #112 for now, and we'll figure out what logo WebAssembly has when we get closer to MVP.

Please also make sure you're a member of the W3C community as explained in [Contributing.md](Contributing.md).

License-wise we probably want something else than MIT, likely the same as the HTML5 logos as detailed in #112.

**Comment by armanx64** [comment]
Sorry about licence part. Which is needed, how you think?

**Comment by jfbastien** [comment]
@armanx64 we haven't really discussed it, but it we want to go with an HTML5 logo feel then we should follow what they do and use Creative Commons Attribution 3.0. We may want something else too, it's too early to figure out.

**Comment by armanx64** [comment]
Sorry again for disturbing.

**Comment by jfbastien** [comment]
You're not disturbing at all! Your participation is very welcome, it's just
about keeping all the logos in that issue for now so it's easier to get
back to when we add a logo.

**Pull request closed without merging**
