### PR TITLE
WebAssembly JS API declaration file for TypeScript

### PR DESCRIPTION
**Pull request by nidin**

### CODE REVIEW

**Comment by jfbastien** [comment]
I think this would be better as a sub-project undef github.com/WebAssembly. We could make you its owner, as long as you're OK maintaining the correspondence to JS as new APIs are added.

The license would have to match WebAssembly's, and you'd have to be a CG member.

I'd then link to that repo from here.

**Comment by nidin** [comment]
That's Perfect. I am Ok to maintain it. License of WebAssembly is **Apache License 2.0** right?
Well What is CG stands for and How to become a CG member?

**Comment by jfbastien** [comment]
Great. Let's wait to see what others think. This is just my opinion, I can't unilaterally decide 😄 

Here's my thinking: our aim is to support multiple languages (C / C++ and others), as well as multiple embeddings. I see TypeScript as another embedding, very close to JavaScript. We've put JS.md front and center because executing on the Web is a big reason we started WebAssembly, and standardizing it is important. I don't think WebAssembly should go out of its way to explicitly support everything under the sun<sup>† </sup>, but TypeScript is super simple given how close it is to JS, and is compatible with our "web embedding" goal. Having a compatible TypeScript declaration seems like pure goodness.

Having this specification "close" to WebAssembly loans it credibility and it is therefore crucial that it be maintained accordingly. It's also crucial that it be license-compatible and follow the CG rules, because we want WebAssembly usage to be simple, not a mishmash of licenses.

The [contributing guide](https://github.com/WebAssembly/design/blob/master/Contributing.md) has information on general contribution, such as joining the CG. The license we've used throughout is indeed Apache 2.0, unless prior existing work wasn't (e.g. LLVM).

A minimal repository would be similar to [spec's top level folder](https://github.com/WebAssembly/spec): contributing, readme, license, Travis CI.

----

<sup>† </sup> *Explicitly supporting* doesn't mean we don't want WebAssembly to let anyone implement anything! By this I simply mean that supporting everything isn't something that we can tackle: it would drag us down.

**Comment by nidin** [comment]
Nice and sounds good to me.
- [x] Acquainting yourself with the Code of Ethics and Professional Conduct. ✅ 
- [x] Reading the WebAssembly design. ✅ 
- [x] Joining the IRC channel irc://irc.w3.org:6667/#webassembly. ✅ 
- [x] Please join the W3C Community Group ✅ 

⚠️  I am not representing any organization.

**Comment by rossberg-chromium** [comment]
Agreed with @jfbastien.

**Comment by jfbastien** [comment]
Looks like everyone is fine with this.

**Pull request merged**
