### PR TITLE
Postorder opcodes

### PR DESCRIPTION
**Pull request by titzer**
This is a carry-over of #628 to binary version 11.

### CODE REVIEW

**Comment by rossberg-chromium** [comment]
LGTM

**Comment by sunfishcode** [comment]
lgtm

**Comment by qwertie** [comment]
Can someone point me to a rationale or discussion about the change to postorder?

**Comment by titzer** [comment]
https://docs.google.com/presentation/d/1OQ2SY3ywZVRPNZDaOHyNCQGTmZ3LGrW_9vqjO8wL6AE/edit?usp=sharing

**Pull request merged**
