### PR TITLE
Move select out of the "control flow opcodes" section.

### PR DESCRIPTION
**Pull request by sunfishcode**
And into the "Basic opcodes" section, renumbering the remainder of the
section accordingly.

This is for the binary_0xc branch, and is one step of a broader opcode reorganization.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm

**Comment by titzer** [comment]
I think we should do a big one-step reorganization instead of small steps, and the reorganization needs to balance a couple of things: compressibility, extensibility, and logical consistency. In particular, some advice from the Brotli compression folks suggested that the opcodes should be organized to reduce entropy and allow the compression algorithm to do a better job.

**Comment by sunfishcode** [comment]
If someone wants to compute a Brotli-friendly order, that's fine with me. If we wish to balance it with logical consistency, organizing the opcodes for logical consistency before we begin will simplify the process.

**Comment by rossberg-chromium** [comment]
Should be subsumed by #826 now.

**Pull request closed without merging**
