### PR TITLE
Remove GC.md

### PR DESCRIPTION
**Pull request by jfbastien**
We should removing GC.md as part of #1066. It's more aspirational that concrete, and we're now tracking GC work with #1079 as well as in https://github.com/WebAssembly/gc/.

Caveat before removing this:

* Other pages link to it. I'll clean up.
* Some of the content may still be valid. We should move it to the GC proposal instead so it doesn't become stale.

### CODE REVIEW

**Comment by jfbastien** [comment]
Luke / Andreas: what do you think should be moved to the GC proposal from this page?

**Comment by lukewagner** [comment]
Yeah, GC.md was just a stopgap early on when the question kept coming up.

**Comment by jfbastien** [comment]
Is there anything you think should be migrated to https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md ?

**Comment by lukewagner** [comment]
I guess, now that you mention it, the "JS integration" and "WebIDL integration" subsections would be separate proposals (that build on top of gc/Overview.md).  They're just sketches though (and a bit antiquated by now), so out of place w.r.t the rest of the design repo, which describes the shipping status quo.  So I'm fine removing them.

**Comment by jfbastien** [comment]
I can move them to a tracking issue in the design repo.

**Comment by rektide** [comment]
Even if it's a place-holder, having some kind of information available that links WebAssembly to the rest of the Web Platform seems like a really good healthy thing. I'd expect that not having this would cause a lot of silent head scratching and create a support burden for randos like me wandering in wondering what the story is.

I'd like to see a very minimal gc/JS.md and/or gc/WebIDL.md created before dropping GC.md, even if just a placeholder, to prevent confusion from spreading. It's important to leave some kind of stake in the ground here. Links in these documents to a tracking issue would be appropriate and helpful.

**Pull request merged**
