### PR TITLE
Host bindings => Interface types

### PR DESCRIPTION
**Pull request by pygy**

### CODE REVIEW

**Comment by binji** [comment]
This document hasn't been kept up to date, it's probably better to redirect to https://github.com/WebAssembly/proposals, which has been.

**Comment by pygy** [comment]
So you'd suggest scraping `FutureFeatures.md` (replacing it with a stub, because LinkRotSucks<sup>TM</sup>), and updating the corresponding links elsewhere in these docs?

**Comment by binji** [comment]
Yes, I think that would be better. Thanks!

**Comment by sunfishcode** [comment]
The table in question has now been moved to https://github.com/WebAssembly/proposals.

**Pull request closed without merging**
