### PR TITLE
Point to the Streams Standard as that's actively being worked on

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by jfbastien** [comment]
You'll have to join the [W3C Community Group](https://www.w3.org/community/webassembly) before we can merge this.

**Comment by annevk** [comment]
No thanks!

**Comment by MikeHolman** [comment]
Ok, then I'll close this. I'm sure we will update when we start investing work in this area.

**Comment by domenic** [comment]
Are we allowed to file issues without being in the community group? Or will those get closed too?

**Comment by MikeHolman** [comment]
@domenic see #199 (we're kind of still figuring this out)

**Comment by sideshowbarker** [comment]
So as indicated in other updates now shown here, in the interest of getting this resolved, I duplicated @annevk’s patch at #211. (From the resolution that’s emerged at #199 it seems like this, being a minor typo-level change, could be merged even with a patch from someone who’s not a member of the CG. But in this case it’s moot since I am already a member of the CG and have signed off on the CLA.)

**Comment by annevk** [comment]
Thanks @sideshowbarker! I didn't realize that removing my fork made merging this impossible. At the top it still shows exactly the change I proposed and such. Weird.

**Pull request closed without merging**
